=== BlueAndi/vscp-framework/tools/vscp-mdf-schema/mdf.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--

The MIT License (MIT)

Copyright (c) 2014 - 2018, Andreas Merkle
http://www.blue-andi.de
vscp@blue-andi.de

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

********************************************************************************
This xml schema defines the VSCP module description file (MDF) format.
********************************************************************************
-->

<schema targetNamespace="http://www.blue-andi.de/vscp/mdf/1.0" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:mdf="http://www.blue-andi.de/vscp/mdf/1.0" attributeFormDefault="unqualified">

    <element name="vscp">
        <annotation>
        	<documentation>Top level element of the module description file (MDF).</documentation>
        </annotation>
        <complexType>
        	<sequence>
        		<element name="module" type="mdf:module-type"
        			minOccurs="1" maxOccurs="1">
        		</element>
        	</sequence>
        	<attribute name="version" type="string" use="optional" default="1.0">
        		<annotation>
        			<documentation>Version of the mdf schema. "1.0" is the default.</documentation>
        		</annotation></attribute>
        </complexType>
    </element>

    <complexType name="module-type">
    	<sequence>
    		<element name="name" minOccurs="1" maxOccurs="1">
    			<complexType>
    				<simpleContent>
    					<extension base="string">
    						<attribute name="lang" type="language"
    							use="optional" default="en">
    						</attribute>
    					</extension>
    				</simpleContent>
    			</complexType>
    		</element>
    		<element name="model" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="version" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="changed" type="date" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="description" minOccurs="1" maxOccurs="1">
    			<complexType>
    				<simpleContent>
    					<extension base="string">
    						<attribute name="lang" type="language"
    							use="optional" default="en">
    						</attribute>
    					</extension>
    				</simpleContent>
    			</complexType>
    		</element>
    		<element name="infourl" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="buffersize" type="unsignedInt" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="manufacturer" type="mdf:manufacturer-type"
    			minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="picture" type="mdf:picture-type"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="firmware" type="mdf:firmware-type"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="manual" type="mdf:manual-type" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="boot" type="mdf:boot-type" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="registers" type="mdf:registers-type"
    			minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="abstractions" type="mdf:abstractions-type"
    			minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="alarm" type="mdf:alarm-type" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="dmatrix" type="mdf:dmatrix-type"
    			minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="events" type="mdf:events-type" minOccurs="1"
    			maxOccurs="1">
    		</element>
    	</sequence>

    </complexType>

    <complexType name="manufacturer-type">
    	<sequence>
    		<element name="name" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="address" type="mdf:address-type"
    			minOccurs="0" maxOccurs="unbounded">
    		</element>
    		<element name="telephone" type="mdf:telephone-type"
    			minOccurs="0" maxOccurs="unbounded">
    		</element>
    		<element name="email" type="mdf:email-type" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    		<element name="web" type="mdf:web-type" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="address-type">
    	<sequence>
    		<element name="street" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="city" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="postcode" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="country" type="string" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="telephone-type">
    	<sequence>
    		<element name="number" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="description" minOccurs="1" maxOccurs="1">
    			<complexType>
    				<simpleContent>
    					<extension base="string">
    						<attribute name="lang" type="language" use="optional" default="en">
    						</attribute>
    					</extension>
    				</simpleContent>
    			</complexType>
    		</element>
    	</sequence>
    </complexType>

    <complexType name="email-type">
    	<sequence>
    		<element name="address" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="description" minOccurs="1" maxOccurs="1">
    			<complexType>
    				<simpleContent>
    					<extension base="string">
    						<attribute name="lang"
    							type="language" use="optional" default="en">
    						</attribute>
    					</extension>
    				</simpleContent>
    			</complexType>
    		</element>
    	</sequence>
    </complexType>

    <complexType name="web-type">
    	<sequence>
    		<element name="address" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="description" minOccurs="1" maxOccurs="1">
    			<complexType>
    				<simpleContent>
    					<extension base="string">
    						<attribute name="lang" type="string"
    							use="optional" default="en">
    						</attribute>
    					</extension>
    				</simpleContent>
    			</complexType>
    		</element>
    	</sequence>
    </complexType>

    <complexType name="boot-type">
    	<sequence>
    		<element name="algorithm" type="unsignedInt" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="blocksize" type="unsignedInt" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="blockcount" type="unsignedInt" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="registers-type">
    	<sequence>
    		<element name="reg" type="mdf:reg-type" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="reg-type">
    	<sequence>
    		<group ref="mdf:name-desc-group"/>
    		<element name="access" minOccurs="1" maxOccurs="1" type="mdf:access-type">
    		</element>
    		<element name="valuelist" type="mdf:valuelist-type"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="bit" type="mdf:bit-type" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    	<attribute name="page" type="unsignedShort" use="required"></attribute>
    	<attribute name="offset" type="unsignedByte" use="required"></attribute>
    </complexType>

    <complexType name="valuelist-type">
    	<sequence>
    		<element name="item" type="mdf:item-type" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="item-type">
    	<sequence>
    		<group ref="mdf:name-desc-group"/>
    	</sequence>
    	<attribute name="value" type="mdf:c-hex-type" use="required"></attribute>
    </complexType>

    <complexType name="bit-type">
    	<sequence>
    		<group ref="mdf:name-desc-group"/>
    	</sequence>
    	<attribute name="pos" type="unsignedByte" use="required"></attribute>
    	<attribute name="default" type="boolean" use="optional"></attribute>
    </complexType>

    <complexType name="abstraction-type">
    	<sequence>
    		<group ref="mdf:name-desc-group" />
    		<element name="access" type="mdf:access-type"></element>
    	</sequence>
    	<attribute name="type" type="string" use="required"></attribute>
    	<attribute name="page" type="unsignedShort" use="required"></attribute>
    	<attribute name="offset" type="unsignedByte" use="required"></attribute>
    	<attribute name="id" type="string" use="required"></attribute>
    </complexType>

    <simpleType name="access-type">
    	<restriction base="string">
    		<enumeration value="r"></enumeration>
    		<enumeration value="w"></enumeration>
    		<enumeration value="rw"></enumeration>
    	</restriction>
    </simpleType>

    <complexType name="alarm-type">
    	<sequence>
    		<element name="bit" type="mdf:bit-type" minOccurs="8" maxOccurs="8"></element>
    	</sequence>
    </complexType>

    <complexType name="dmatrix-type">
    	<sequence>
    		<element name="level" type="unsignedInt" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="start" minOccurs="1" maxOccurs="1">
    			<complexType>
    				<attribute name="page" type="unsignedShort" use="required"></attribute>
    				<attribute name="offset" type="unsignedByte" use="required"></attribute>
    			</complexType>
    		</element>
    		<element name="rowcnt" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="action" type="mdf:action-type" minOccurs="1"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="action-type">
    	<sequence>
    		<group ref="mdf:name-desc-group"/>
    		<element name="param" minOccurs="1" maxOccurs="1">
    			<complexType>
    				<sequence>
    					<group ref="mdf:name-desc-group" />
    					<element name="data" minOccurs="1"
    						maxOccurs="1">
    						<complexType>
    							<sequence>
    				                <group ref="mdf:name-desc-group"/>
    							</sequence>
    							<attribute name="offset" type="int">
    							</attribute>
    						</complexType>
    					</element>
    				</sequence>
    			</complexType>
    		</element>
    	</sequence>
    	<attribute name="code" type="mdf:c-hex-type" use="required"></attribute>
    </complexType>

    <complexType name="events-type">
    	<sequence>
    		<element name="event" type="mdf:event-type" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="event-type">
    	<sequence>
    		<group ref="mdf:name-desc-group"/>
    		<element name="priority" type="unsignedByte" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="data" minOccurs="0" maxOccurs="unbounded">
    			<complexType>
    				<sequence>
    					<group ref="mdf:name-desc-group"/>
    				</sequence>
    				<attribute name="offset" type="unsignedShort"
    					use="required">
    				</attribute>
    			</complexType>
    		</element>
    	</sequence>
    	<attribute name="class" type="mdf:c-hex-type" use="required"></attribute>
    	<attribute name="type" type="mdf:c-hex-type" use="required"></attribute>
    </complexType>

    <group name="name-desc-group">
        <sequence>
        	<element name="name" minOccurs="1" maxOccurs="1">
        		<complexType>
        			<simpleContent>
        				<extension base="string">
        					<attribute name="lang" type="language"
        						use="optional" default="en">
        					</attribute>
        				</extension>
        			</simpleContent>
        		</complexType>
        	</element>
        	<element name="description" minOccurs="1" maxOccurs="1">
        		<complexType>
        			<simpleContent>
        				<extension base="string">
        					<attribute name="lang" type="language"
        						use="optional" default="en">
        					</attribute>
        				</extension>
        			</simpleContent>
        		</complexType>
        	</element>
        </sequence>
    </group>

    <complexType name="abstractions-type">
    	<sequence>
    		<element name="abstraction" type="mdf:abstraction-type" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <simpleType name="c-hex-type">
    	<restriction base="string">
    		<pattern value="[0-9]+"></pattern>
    		<pattern value="0x[0-9a-fA-F]+"></pattern>
    	</restriction>
    </simpleType>

    <complexType name="picture-type">
    	<sequence>
    		<element name="description">
    			<complexType>
    				<simpleContent>
    					<extension base="string">
    						<attribute name="lang" type="language" use="optional" default="en">
    						</attribute>
    					</extension>
    				</simpleContent>
    			</complexType>
    		</element>
    	</sequence>
    	<attribute name="path" type="string" use="required"></attribute>
    	<attribute name="format" type="string" use="required"></attribute>
    	<attribute name="size" type="unsignedLong" use="required"></attribute>
    </complexType>

    <complexType name="firmware-type">
    	<sequence>
    		<element name="description">
    			<complexType>
    				<simpleContent>
    					<extension base="string">
    						<attribute name="lang" type="language" use="optional" default="en">
    						</attribute>
    					</extension>
    				</simpleContent>
    			</complexType>
    		</element>
    	</sequence>
    	<attribute name="path" type="string" use="required"></attribute>
    	<attribute name="format" type="string" use="required"></attribute>
    	<attribute name="size" type="unsignedInt" use="required"></attribute>
    	<attribute name="date" type="date" use="required"></attribute>
    	<attribute name="version_major" type="string" use="required"></attribute>
    	<attribute name="version_minor" type="string" use="required"></attribute>
    	<attribute name="version_subminor" type="string" use="required"></attribute>
    </complexType>

    <complexType name="manual-type">
    	<sequence>
    		<element name="description">
    			<complexType>
    				<simpleContent>
    					<extension base="string">
    						<attribute name="lang" type="language" use="optional" default="en">
    						</attribute>
    					</extension>
    				</simpleContent>
    			</complexType>
    		</element>
    	</sequence>
    	<attribute name="path" type="string" use="required"></attribute>
    	<attribute name="lang" type="language" use="optional" default="en"></attribute>
    	<attribute name="format" type="string" use="required"></attribute>
    </complexType>
</schema>

=== BlueAndi/vscp-framework/examples/pc/mdf/exp02.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!--

The MIT License (MIT)

Copyright (c) 2014 - 2015, Andreas Merkle
http://www.blue-andi.de
vscp@blue-andi.de

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

********************************************************************************
This module description file (MDF) is for the VSCP framework example PC.

$Author: amerkle $
$Rev: 449 $
$Date: 2015-01-05 20:23:52 +0100 (Mo, 05 Jan 2015) $
********************************************************************************
-->

<vscp xmlns="http://www.blue-andi.de/vscp/mdf/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.blue-andi.de/vscp/mdf/1.0 mdf.xsd ">

    <module>

        <name>Example project PC</name>
        <model>A</model>
        <version>0.1.0</version>
        <changed>2014-12-20</changed>
        <description lang="en">The node contains a basic example for using VSCP.</description>
        <infourl></infourl>

        <!-- Max package size a node can receive -->
        <buffersize>8</buffersize>

        <!-- Manufacturer -->
        <manufacturer>
            <name>blue-andi</name>
            <address>
                <street>Schubertstr. 1</street>
                <city>Roggenburg</city>
                <postcode>89297</postcode>
                <country>Germany</country>
            </address>
            <telephone>
                <number>+49 ...</number>
                <description lang="en" >:-)</description>
            </telephone>
            <email>
                <address>web@blue-andi.de</address>
                <description lang="en">Support email</description>
            </email>
            <web>
                <address>http://www.blue-andi.de</address>
                <description lang="en">Main web address</description>
            </web>
        </manufacturer>

        <!-- Boot loader information -->
        <boot>
            <algorithm>0</algorithm>
            <blocksize>0</blocksize>
            <blockcount>0</blockcount>
        </boot>

        <!-- Register space -->
        <registers>

            <!-- ********** Page 0 ********** -->

            <reg page="0" offset="0" >
                <name lang="en">Zone</name>
                <description lang="en">Zone this module belongs to.</description>
                <access>rw</access>
            </reg>

            <reg page="0" offset="1" >
                <name lang="en">Sub-zone</name>
                <description lang="en">Sub-zone this module belongs to.</description>
                <access>rw</access>
            </reg>

            <!-- ********** Page 1 ********** -->

            <!-- DM Row 1 -->
            <reg page="1" offset="0" >
                <name lang="en">Decision matrix row 1: oaddr</name>
                <description lang="en">Originating address: Set to nickname for node that should trigger action.
oaddr is the originating address. We are only interested in messages from the node given here. 0x00 is segment controller and 0xff is a node without a nickname.
If bit 6 of flags is set, oaddr will not be checked and events from all nodes will be accepted.</description>
                <access>rw</access>
            </reg>

            <reg page="1" offset="1" >
                <name lang="en">Decision matrix row 1: flags</name>
                <description lang="en">Flags: Set selection behaviour.
The enable bit can be used to disable a decion matrix row while it is edited.
The zone and sub-zone bits can be activated to have a check on the zone/sub-zone information of an event.
The zone/sub-zone must match the one of the event to trigger the DM row.</description>
                <access>rw</access>
                <bit pos="0" default="0" >
                    <name lang="en">Class filter bit 8</name>
                    <description lang="en">Defines the 9th bit of the class filter.</description>
                </bit>
                <bit pos="1" default="0" >
                    <name lang="en">Class mask bit 8</name>
                    <description lang="en">Defines the 9th bit of the class mask.</description>
                </bit>
                <bit pos="2" default="false" >
                    <name lang="en">Reserved bit</name>
                    <description lang="en">This bit is not used.</description>
                </bit>
                <bit pos="3" default="false" >
                    <name lang="en">Sub-zone match</name>
                    <description lang="en">If set to one, sub-zone must match to trigger DM entry action.</description>
                </bit>
                <bit pos="4" default="false" >
                    <name lang="en">Zone match</name>
                    <description lang="en">If set to one, zone must match to trigger DM entry action.</description>
                </bit>
                <bit pos="5" default="false" >
                    <name lang="en">Hardcoded</name>
                    <description lang="en">If set to one, the originating address must be hardcoded to trigger DM entry action.</description>
                </bit>
                <bit pos="6" default="false" >
                    <name lang="en">Check Originating address</name>
                    <description lang="en">If set to one, the originating address should be checked and match to trigger DM entry action.</description>
                </bit>
                <bit pos="7" default="false" >
                    <name lang="en">Enable</name>
                    <description lang="en">Enable (1) or disable (0) the decison matrix row.</description>
                </bit>
            </reg>

            <reg page="1" offset="2" >
                <name lang="en">Decision matrix row 1: Class mask (low 8 bits) </name>
                <description lang="en">The lowest 8 bits of the class mask that defines the events that should trigger the action of this decision matrix row.
Bit 8 of the class mask is stored in bit 1 of the flag byte.</description>
                <access>rw</access>
            </reg>

            <reg page="1" offset="3" >
                <name lang="en">Decision matrix row 1: Class filter (low 8 bits)</name>
                <description lang="en">The lowest 8 bits of the class filter that defines the events that should trigger the action of this decision matrix row.
Bit 8 of the class filter is stored in bit 1 of the flag byte.</description>
                <access>rw</access>
            </reg>

            <reg page="1" offset="4" >
                <name lang="en">Decision matrix row 1: Type mask</name>
                <description lang="en">Type mask that defines the events that should trigger the action of this decision matrix row.</description>
                <access>rw</access>
            </reg>

            <reg page="1" offset="5" >
                <name lang="en">Decision matrix row 1: Type filter</name>
                <description lang="en">Type filter that defines the events that should trigger the action of this decision matrix row.</description>
                <access>rw</access>
            </reg>

            <reg page="1" offset="6" >
                <name lang="en">Decision matrix row 1: Action</name>
                <description lang="en">This is the action or operation that should be performed if the filtering is satisfied. Only action code 0×00 is predefined and means No-Operation. All other codes are application specific and typical application defined codes could do measurement, send predefined event etc.</description>
                <access>rw</access>
            </reg>

            <reg page="1" offset="7" >
                <name lang="en">Decision matrix row 1: Action parameter</name>
                <description lang="en">A numeric action parameter can be set and its meaning is application specific.</description>
                <access>rw</access>
            </reg>

            <!-- DM Row 2 -->
            <reg page="1" offset="8" >
                <name lang="en">Decision matrix row 2: oaddr</name>
                <description lang="en">Originating address: Set to nickname for node that should trigger action.
oaddr is the originating address. We are only interested in messages from the node given here. 0x00 is segment controller and 0xff is a node without a nickname.
If bit 6 of flags is set, oaddr will not be checked and events from all nodes will be accepted.</description>
                <access>rw</access>
            </reg>

            <reg page="1" offset="9" >
                <name lang="en">Decision matrix row 2: flags</name>
                <description lang="en">Flags: Set selection behaviour.
The enable bit can be used to disable a decion matrix row while it is edited.
The zone and sub-zone bits can be activated to have a check on the zone/sub-zone information of an event.
The zone/sub-zone must match the one of the event to trigger the DM row.</description>
                <access>rw</access>
